#!/bin/python3

import sys

def aVeryBigSum(n, ar):
    for nums in range(-2^31, 2^31 - 1):
        total = 0
        for nums in ar:
            total += nums
        return total

n = int(input().strip())
ar = list(map(int, input().strip().split(' ')))
result = aVeryBigSum(n, ar)
print(result)
