#!/bin/python3

import sys

if __name__ == "__main__":
    meal_cost = float(input())
    tip_percent = int(input())
    tax_percent = int(input())
    tip = (tip_percent / 100) * meal_cost
    tax = (tax_percent / 100) * meal_cost
    totalCost = meal_cost + tip + tax
print("The total meal cost is " + str(round(totalCost)) + " dollars.")
